* springCloud 相关知识点

** 什么是为服务架构

微服务架构就是通过将单体应用拆分成多个服务，每个服务运行在自己的进程中，服务和服务之间通过轻量级协议进行通信

** 为什么需要学习 springCloud

1. 简化配置 springCloud 基于 springBoot
2. 开箱即用
3. springCloud 每个子模块都解决了微服务的特定问题， 比如 zuul 解决跨域， feigin 和 Ribbon 解决负载均衡 hystrix 解决断路问题。

** springCloud 是什么

解决微服务架构的一系列的基础服务组件的集合，提供了服务注册发现，配置中心，路由，消息总线，负载均衡，断路器等微服务的基础服务。

** springCloud 常用服务

1. eureka
2. config
3. zuul
4. Feign
5. hystrix
6. Ribbon

等

** 什么是 eureka

服务注册中心，子服务通过心跳机制，将服务注册到 eureka 当中

** Eureka 怎么实现高可用

通过搭建集群的方式， eureka 服务之间相互注册。

** Eureka 和 zookeeper 之间的区别

Eureka 使用的是 客户端发现， zookeeper 采用的是服务端发现

** 什么是网关

网关相当于是一个服务的网络架构的入口，所有的请求需要通过网关才能请求到对应的服务

** 网关的作用是什么？

统一的服务管理，权限控制，路由转发， 限流等

** Zuul 是什么

zuul 是 springCloud 成熟的网络解决方案他会根据请求路径不同，网关会定位到指定的服务。

1. 动态路由表， zuul 支持 eureka 手动配置路由，两种都支持
2. 路由定位，根据请求路径zuul 有自己的一套定位服务规则和表达式
3. 反向代理，客户端通过请求请求到网关，网关受理之后将请求转发给对应的服务，拿到结果在响应给客户端

** zuul 的应用场景

对外暴露服务，服务聚合，限流操作

** 常用的网关框架有哪些

zuul nginx gateWay

** zuulFilter 常用方法

run（） 过滤器具体业务，
shouldFilter（）判断过滤是否有效
filterOrder（） 过滤顺序
filterType（） 过滤器设置

** 如何实现 zuul 的动态路由转发

通过 path 配置拦截请求， 通过 serviceId 获取对应服务的列表 在通过 Ribbon 进行负载均衡和转发。

** zuul 如何搭建集群

使用 nginx upstream 设置 zuul 服务集群

** Ribbon是什么

 netflix 公司提供的一开源项目，主要的目的是为客户端提供负载均衡算法

** nginx 与Ribbon 的区别

nginx 服务端负载均衡，是将请求进行拦截，然后通过负载均衡算法，转发到 upstream ，ribbon 是客户端进行负载均衡，
从注册中心读取服务的信息，然后根据负载均衡的方法，想客户端进行请求。

** Ribbon 的原理

Ribbon 通过 discoveryClient 获取服务列表，通过负载均衡算法，比如轮询，随机等方式选取对应的服务信息，进行负载均衡。

** @LoadBalance 的作用

开启客户端负载均衡

** 什么是Hystrix

当一个服务调用另外一个服务，由于网络或者其他原因失败，导致调用者进行等待，请求的越多，资源消耗越大导致服务宕机，导致雪崩效应。

断路器的三种状态
1. 打开，一定次数请求失败，并且服务调用没有恢复的迹象，那么下次就不会请求到该服务。
2. 半打开，短时间内有恢复迹象，断路器会把请求发送给该服务，正常调用时断路器关闭
3. 关闭，服务一直出于可以调用的状态

hystrix 是防止服务雪崩的，通过服务降级，服务熔断，服务隔离，监控等防止雪崩的技术。

** 四种防止雪崩的方式：
1. 服务降级 接口调用失败，就返回空
2. 服务熔断 接口调用失败，就返回一个提前定义好的熔断方法，
3. 服务隔离 隔离服务之间的影响
4. 服务监控 将调用的请求数量等指标记录下来进行监控


** 服务降级底层是如何实现的

Hystrix 实现服务降级功能是通过重写 HystrixCommond中的 getFallBack（）方法，当 Hystrix 执行run 方法或者 construct 方法，执行
发生错误时，调用 fallBack（）方法

** 什么是 Feigin 

Feigin 是一个 声明式的 web 服务客户端，将我们调用服务的方法抽象成方法保存在本地，不需要构建 http请求直接调用接口就可以了。
调用方法，要和本地抽象方法签名一致。

** springCloud 有几种服务调用方式

restemplate
Feigin

** springCloudBus

用于扩展springboot 应用配置，和应用程序的消息通道，bus需要和 mq 结合和 config 配置中心结合，可以进行配置的动态刷新。

** springCloudConfig

springCloud 为分布式系统中的外部配置提供服务和客户端的支持，可以对微服务各个环境下的配置进行一个集中的管理， config 分为 configserver 和 configclient
configserver 负责读取配置文件暴露 httpapi 接口，configClient 通过调用 api 来获取配置

** 配置中心的作用

1. 统一的配置管理
2. 动态刷新配置


