* 工作回顾

  在七月末，经过了三轮面试有幸加入到公司，刚进入公司的时候，对周围的环境充满了新奇，但是给我感受最多是，周围同样作为开发人员，每个人都有着很强的技术能力。
以及项目负责人，和管理管理人员，都拥有着很强的专业技能。让我内心感到庆幸，自己加入了一个很棒的团队。有了很大的工作动力。
  刚刚入职，熟悉了项目开发流程，h之后开始进行项目的开发，最开始是开发了DPAS银行相关功能，也是通过这些功能，对公司的开发流程进行了熟悉。之后，和庆明，大鹏哥，和一帆，
一起开始开发 DSM 数据采集服务。在开发数据采集服务的过程中，对公司的开发流程进行了更加深入的了解，虽然刚开始对一些之前工作中没有使用到的开发文档和规范有些不适应，但是
随着工作的进行，以及阅读《代码整洁之道》后，对公司“规范的文档和详细的设计”，有着很强的认可和理解。这些文档最终会成为公司技术的沉淀。并且是公司产品质量的保证。
  之后，由于公司内部的需要，有幸参与了 CMP 服务的项目开发工作，这个是一个对公司物理机资源管理的一个产品。在产品设计过程中，通过孟哥，郭哥，常哥以及架构师的严格要求，
使我在产品设计的能力上有了明显的提高。经历了近三个月的迭代，在我，和俊豪，还有一帆的共同努力下完成了 CMP 的后端开发工作。并上线运行了 1.0 版本。
  在经历过 CMP 的设计，到开发完成，让我对公司的开发流程有了熟练的掌握，到目前，在进行 MDS 系统服务从设计到开发，以及任务的设置，也有了更好的经验。当然作为技术人员。
在开发过程中的技术提升，也是一定的，在项目开发的过程中掌握了很多，之前没有掌握的技术，如：mongo，kafka 等。现在回想一下，虽然时间不长，感觉自己还是收获满满的，增长了
很多工作经验。

* 工作业绩

1. CMP 服务设计到开发上线
2. MDS 服务设计到开发进行中
3. DMS Client 服务 1.0 版本的功能开发
4. DPAS 虚拟银行相关功能实现

* 存在的不足

1. 经历过 CMP 设计的的过程中，让我认识到了，在对面向对象的理解，功能解耦，项目设计能力的不足，这个方面还需要进行大量的学习和操作来提升。
2. 开发规范上，在之前的工作环境中，开发过程中，在开发规范，代码规约上重视的不够，导致现在，在开发过程中规范问题频发。
3. 文档等细节问题处理上还存在不足。需要更加仔细的处理每一份文档内容。

* 2021 年工作计划

作为一名技术人员，在新的一年里，制定计，进一步提升项目设计能力。在编码能力上对自己提出更高的要求，编写出更加简洁，健壮的代码。
并且不断的向周围的人学习，学习更好的工作方式，和经验来提升自己。
